### ISSUE TITLE
Non-bare-word characters break highlighting

### ISSUE THREAD

**Issue by b-jazz** [atom/language-toml#16]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If a key name contains certain characters, even though double quoted, highlighting shows the key as green instead of red.

### Steps to Reproduce

1. Create the following `.toml` file:

```
foo = "red key"
"foo" = "red key"
"foo bar" = "red key"
"foo:bar" = "green key"
```

2. note that the keys are highlighted in the colors above (or possibly different colors depending on your color theme).

**Expected behavior:** 
all keys are valid toml and should be highlighted in the same color

**Actual behavior:** 
the "foo:bar" key, even though quoted, highlights as a different color 

**Reproduces how often:**
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

$ atom --version && apm --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 3.5.3
git 2.11.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Thanks for the report.  Looking into it now.

(Also, the latest version of Atom is 1.23.3 - please consider updating!)
